# Generated by Django 3.1.2 on 2021-03-20 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='nome')),
                ('email', models.EmailField(max_length=120, verbose_name='email')),
                ('height', models.DecimalField(decimal_places=3, default=0, max_digits=4, verbose_name='altura')),
                ('weight', models.DecimalField(decimal_places=3, default=0, max_digits=4, verbose_name='peso')),
            ],
            options={
                'verbose_name': 'Pessoa',
                'verbose_name_plural': 'Pessoas',
                'ordering': ['-pk'],
                'get_latest_by': 'pk',
            },
        ),
    ]
