# Generated by Django 3.1.2 on 2021-03-21 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='height',
            field=models.IntegerField(default=0, verbose_name='altura'),
        ),
        migrations.AlterField(
            model_name='people',
            name='weight',
            field=models.IntegerField(default=0, verbose_name='peso'),
        ),
    ]
